[GLOBAL]
pants_version = "2.9.0"

backend_packages = [
    "pants.backend.awslambda.python",
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.docformatter",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.lint.isort",
]

[anonymous-telemetry]
enabled = true

[python]
interpreter_constraints = ["==3.8.*"]

[pytest]
version = "pytest>=7.0"
lockfile = "3rdparty/py/pytest/lockfile"