CleanOpenPlatformRole: ${file(./config/${opt:stage}/roles/clean_open_platfrom.yml):Role}
LoadCompanyRole: ${file(./config/${opt:stage}/roles/load_company.yml):Role}
LoadOpenPlatformRole: ${file(./config/${opt:stage}/roles/load_open_platform.yml):Role}
LoadHubSpotRole: ${file(./config/${opt:stage}/roles/load_hubspot.yml):Role}
