python_sources(name="lib")

python_awslambda(
    name="lambda",
    runtime="python3.8",
    handler="handler:hello",
    description="AWS Lambda Hello World example",
)

python_tests(
    name="tests",
)