service: etl-dynamodb

frameworkVersion: '3'

plugins:
  - serverless-package-external

custom:
  packageExternal:
    external:
      - '../../flowaccount'

provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-1
  layers:
    - arn:aws:lambda:ap-southeast-1:697698820969:layer:aws-data-wrangler-layer-py3-8:1

functions:
  extract-open-platform:
    handler: handlers/extract_open_platform.handle
  
  clean-open-platform:
    handler: handlers/clean_open_platform.handle
    role: cleanOpenPlatformRole
    description: Clean new export manifest summary, manifest files and records
    events:
      - s3:
          bucket: pipat-raw-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: dynamodb/tables/
            - suffix: .json
          existing: true
  
  load-open-platform:
    handler: handlers/load_open_platform.handle
    events:
      - s3:
          bucket: pipat-clean-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: dynamodb/tables/flowaccount-open-platform-company-user-v2/
            - suffix: .parquet
          existing: true

resources:
  Resources:
    cleanOpenPlatformRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: EtlDynamoDBCleanOpenPlatformRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: EtlDynamoDBCleanOpenPlatformtPolicy
            PolicyDocument: 
              Version: '2012-10-17'
              Statement:
                # Allow create logging group
                - Effect: Allow
                  Action:
                    - logs:CreateLogStream
                    - logs:CreateLogGroup
                  Resource:
                    - "arn:aws:logs:ap-southeast-1:697698820969:log-group:/aws/lambda/etl-dynamodb-dev*:*"
                # Allow logging
                - Effect: Allow
                  Action:
                    - logs:PutLogEvents
                  Resource:
                    - "arn:aws:logs:ap-southeast-1:697698820969:log-group:/aws/lambda/etl-dynamodb-dev*:*:*"
                # Allow reading manifest from raw bucket
                - Effect: Allow
                  Action:
                    - s3:GetObject
                  Resource:
                    - arn:aws:s3:::pipat-raw-bucket/*
                # Allow writing manifest to clean bucket
                - Effect: Allow
                  Action:
                    - s3:PutObject
                  Resource:
                    - arn:aws:s3:::pipat-clean-bucket/*
                # Allow all Glue actions
                - Effect: Allow
                  Action:
                    - glue:*
                  Resource:
                    - "*"