service: etl-dynamodb

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-1
  layers:
    - arn:aws:lambda:ap-southeast-1:697698820969:layer:aws-data-wrangler-layer-py3-8:1

functions:
  extract-open-platform:
    handler: handlers/extract_open_platform.handle
  
  clean-open-platform:
    handler: handlers/clean_open_platform.handle
    events:
      - s3:
          bucket: pipat-raw-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: dynamodb/tables/flowaccount-open-platform-company-user-v2/
            - suffix: .json
          existing: true
  
  load-open-platform:
    handler: handlers/load_open_platform.handle
    events:
      - s3:
          bucket: pipat-clean-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: dynamodb/tables/flowaccount-open-platform-company-user-v2/
            - suffix: .parquet
          existing: true