service: forward-dynamodb-cdc

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, "staging"}
  region: ap-southeast-1
  environment:
    SRC_BUCKET: ${env:SRC_BUCKET}
    SRC_PREFIX: ${env:SRC_PREFIX}
    DST_BUCKET: ${env:DST_BUCKET}
    DST_PREFIX: ${env:DST_PREFIX}
    DST_AWS_ID: ${env:DST_AWS_ID}

package:
  patterns:
    - '!node_modules/**'
    - '!package-lock.json'
    - '!__pycache__/**'
    - '!.pytest_cache/**'
    - '!BUILD'
    - '!**/BUILD'

functions:
  open-platform:
    handler: handler.handle
    description: Copy open platform table's CDC files to another S3 bucket
    role: openPlatformRole
    environment:
      SRC_PREFIX: ${env:SRC_PREFIX}/tables/flowaccount-open-platform-company-user-v2
      DST_PREFIX: ${env:SRC_PREFIX}/tables/flowaccount-open-platform-company-user-v2
    events:
      - s3:
          bucket: ${env:SRC_BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${env:SRC_PREFIX}/tables/flowaccount-open-platform-company-user-v2
            - suffix: .json
          existing: true

resources:
  Resources:
    openPlatformRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ForwardDynamoDBCDCOpenPlatformRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ForwardDynamoDBCDCOpenPlatformPolicy
            PolicyDocument: 
              Version: '2012-10-17'
              Statement:
              # Allow create logging group
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:CreateLogGroup
                Resource:
                  - "arn:aws:logs:::log-group:/aws/lambda/${self:service}-${opt:stage}*:*"
              # Allow logging
              - Effect: Allow
                Action:
                  - logs:PutLogEvents
                Resource:
                  - "arn:aws:logs:::log-group:/aws/lambda/${self:service}-${opt:stage}*:*:*"
              - Effect: "Allow"
                Action:
                  - "s3:GetObject"
                Resource:
                  - "arn:aws:s3:::${env:SRC_BUCKET}/${env:SRC_PREFIX}/tables/flowaccount-open-platform-company-user-v2*"
              - Effect: "Allow"
                Action:
                  - "s3:PutObject"
                Resource:
                  - "arn:aws:s3:::${env:DST_BUCKET}/${env:DST_PREFIX}/tables/flowaccount-open-platform-company-user-v2/*"