RedShiftSecretArn: arn:aws:secretsmanager:${aws:region}:${aws:accountId}:secret:pipat-etl-redshift-lxoxVP
HubSpotTokenSecretArn: arn:aws:secretsmanager:${aws:region}:${aws:accountId}:secret:hubspot-sandbox-token-E9SDg5
