Policy:
  PolicyName: EtlDynamoDBLoadHubSpotStreamingPolicy
  PolicyDocument: 
    Version: '2012-10-17'
    Statement:
      # Allow create logging group
      - Effect: Allow
        Action:
          - logs:CreateLogStream
          - logs:CreateLogGroup
        Resource:
          - "arn:aws:logs:${aws:region}:${aws:accountId}:log-group:/aws/lambda/${self:service}-${opt:stage}*:*"
      # Allow logging
      - Effect: Allow
        Action:
          - logs:PutLogEvents
        Resource:
          - "arn:aws:logs:${aws:region}:${aws:accountId}:log-group:/aws/lambda/${self:service}-${opt:stage}*:*:*"
      # Allow reading from clean bucket
      - Effect: Allow
        Action:
          - s3:ListBucket
        Resource:
          - arn:aws:s3:::${file(./config/${opt:stage}/buckets.yml):CleanBucket}
      # Allow reading from clean bucket
      - Effect: Allow
        Action:
          - s3:GetObject
        Resource:
          - arn:aws:s3:::${file(./config/${opt:stage}/buckets.yml):CleanBucket}/*
      # Allow writing to service bucket
      - Effect: Allow
        Action:
          - s3:PutObject
        Resource:
          - arn:aws:s3:::${file(./config/${opt:stage}/buckets.yml):HubSpotSvcBucket}/*

