RedShiftSecretArn: arn:aws:secretsmanager:${aws:region}:${aws:accountId}:secret:lambda-prod/secret/redshift-8IZCLY
HubSpotTokenSecretArn: arn:aws:secretsmanager:${aws:region}:${aws:accountId}:secret:app-secrets-i3f0te
